@echo off
setlocal EnableDelayedExpansion

REM Check command line argument to determine cleanup level
if /I "%~1"=="all" goto cleanall
if /I "%~1"=="help" goto usage
if /I "%~1"=="?" goto usage

REM Default: basic clean behavior (like Makefile clean target)
echo Performing basic cleanup...

REM Clean auxiliary files generated by LaTeX using latexmk
if exist "sustechthesis-example.tex" (
  latexmk -c sustechthesis-example
)

if exist "sustechthesis-example-report.tex" (
  latexmk -c sustechthesis-example-report
)

if exist "sustechthesis.dtx" (
  latexmk -c sustechthesis.dtx
)

REM Delete common auxiliary files that might remain
call :delete_files *.aux *.bbl *.blg *.toc *.lof *.lot *.out *.fls *.fdb_latexmk *.synctex.gz *.bcf *.run.xml *.xdv *.idv *.lg *.xwm

REM Delete minted temporary directories
call :delete_dirs _minted-*

REM Delete temporary files with tilde
call :delete_files *~

REM Delete markdown-related temporary files
call :delete_files *_markdown_*.tex *_markdown_* *.markdown.*

goto completed

:cleanall
echo Performing full cleanup (cleanall)...

REM Clean auxiliary files generated by LaTeX using latexmk
if exist "sustechthesis-example.tex" (
  latexmk -c sustechthesis-example
)

if exist "sustechthesis-example-report.tex" (
  latexmk -c sustechthesis-example-report
)

if exist "sustechthesis.dtx" (
  latexmk -c sustechthesis.dtx
)

REM Delete common auxiliary files that might remain
call :delete_files *.aux *.bbl *.blg *.toc *.lof *.lot *.out *.fls *.fdb_latexmk *.synctex.gz *.bcf *.run.xml *.xdv *.idv *.lg *.xwm

REM Delete minted temporary directories
call :delete_dirs _minted-*

REM Delete temporary files with tilde
call :delete_files *~

REM Delete markdown-related temporary files
call :delete_files *_markdown_*.tex *_markdown_* *.markdown.*

REM Additionally delete generated class files and PDFs (cleanall behavior)
call :delete_files sustechthesis.cls dtx-style.sty

call :delete_files sustechthesis.pdf sustechthesis-example.pdf sustechthesis-example-report.pdf

REM Delete test-related directories
call :delete_dirs public-test dist

:completed
echo Cleanup operation completed.
goto end

:delete_files
del /Q %* 2>nul
goto :eof

:delete_dirs
for /d %%d in (%*) do (
  if exist "%%d" (
    rmdir /s /q "%%d" 2>nul
  )
)
goto :eof

:usage
echo Usage:
echo   clean.bat        - Basic cleanup (default)
echo   clean.bat all    - Full cleanup (removes generated files too)
echo   clean.bat help   - Show this help

:end
pause